### ISSUE TITLE
Minor bug -> 'datasets summary genome taxon' produces runtime error

### ISSUE THREAD

**Issue by davised** [ncbi/datasets#22]
**Error Summary**

Instead of producing a help/usage message, `datasets summary genome taxon` produces a runtime error.

**Version**

Latest 10.5.1

**Command**

```
$ datasets summary genome taxon
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main/datasets/datasets.glob..func22(0xc01180, 0xc36520, 0x0, 0x0)
        /export/home/tomcat/TeamCity/Agent5/work/c6e6852d9a243866/dataloader/apps/public/Datasets/datasets/datasets/SummaryGenomeTaxon.go:65 +0x208
github.com/spf13/cobra.(*Command).execute(0xc01180, 0xc36520, 0x0, 0x0, 0xc01180, 0xc36520)
        /export/home/tomcat/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xc03640, 0x4435da, 0xbc4d60, 0xc000000180)
        /export/home/tomcat/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /export/home/tomcat/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main/datasets/datasets.Execute()
        /export/home/tomcat/TeamCity/Agent5/work/c6e6852d9a243866/dataloader/apps/public/Datasets/datasets/datasets/root.go:73 +0x31
main.main()
        /export/home/tomcat/TeamCity/Agent5/work/c6e6852d9a243866/dataloader/apps/public/Datasets/datasets.go:8 +0x20
```

Adding a `-h` produces help message, as expected.

**Comment by BradHolmes** [comment]
Thank you for the report.  We have put this into our internal backlog.

I'm going to leave this issue open until it is implemented and deployed.

**Comment by BradHolmes** [comment]
This is now fixed in the latest version:

```
> ./datasets version
10.7.1
> ./datasets summary genome taxon
Error: accepts 1 arg(s), received 0
Usage:
  datasets summary genome taxon [flags]

Examples:
  datasets summary genome taxon human
  datasets summary genome taxon "mus musculus"
  datasets summary genome taxon 10116

Flags:
  -h, --help              help for taxon
      --tax-exact-match   exclude sub-species when a species-level taxon is specified

Global Flags:
      --assmaccs       return only assembly accessions
      --limit string   limit the number of genome summaries returned
                       * "all": returns all matching genome summaries
                       * "none": returns only the number of matching genome summaries
                       * a number: returns the specified number of matching genome summaries
                        (default "all")
      --refseq         limit to RefSeq (GCF_) assemblies

accepts 1 arg(s), received 0
```
