### ISSUE TITLE
Downloading large datasets

### ISSUE THREAD

**Issue by ganiatgithub** [ncbi/datasets#231]
Hi Eric,

I seem to have the same issue with `datasets version: 14.26.0`. Here are my error messages with two trials I had:

```
Collecting 1,520  records [================================================] 100% 1520/1520
Downloading: zou_2019.zip    593kB done
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x923899]

goroutine 11 [running]:
datasets_cli/v2/datasets.baseRetryPolicy(...)
        apps/public/Datasets/v2/datasets/datasets/root.go:225
datasets_cli/v2/datasets.DefaultRetryPolicy({0xb91b10, 0xc00003c138}, 0x0, {0xc0003ba060?, 0x4e24c7?})
        apps/public/Datasets/v2/datasets/datasets/root.go:195 +0x59
github.com/hashicorp/go-retryablehttp.(*Client).Do(0xc0000eb880, 0xc0005707c8)
        external/com_github_hashicorp_go_retryablehttp/client.go:631 +0x61e
github.com/hashicorp/go-retryablehttp.(*RoundTripper).RoundTrip(0xc00000cfa8, 0xc000593bc0?)
        external/com_github_hashicorp_go_retryablehttp/roundtripper.go:44 +0x7d
datasets_cli/v2/datasets.LoggingRoundTripper.RoundTrip({{0xb8bdc0?, 0xc00000cfa8?}}, 0xc0001c0400)
        apps/public/Datasets/v2/datasets/datasets/root.go:522 +0x21d
net/http.send(0xc0001c0400, {0xb8e580, 0xc0001ac550}, {0xa7b3a0?, 0x1?, 0x0?})
        GOROOT/src/net/http/client.go:252 +0x5d8
net/http.(*Client).send(0xc00039c8a0, 0xc0001c0400, {0x480e49?, 0x630000c000206f06?, 0x0?})
        GOROOT/src/net/http/client.go:176 +0x9b
net/http.(*Client).do(0xc00039c8a0, 0xc0001c0400)
        GOROOT/src/net/http/client.go:725 +0x8f5
net/http.(*Client).Do(...)
        GOROOT/src/net/http/client.go:593
datasets_cli/v2/datasets.processHTTPRequest(0xc00042de50?, 0xc000593bc0?)
        apps/public/Datasets/v2/datasets/datasets/Rehydrate.go:150 +0xb9
datasets_cli/v2/datasets.downloadFileWorker.func2(0xc00003d290, 0xc00042df38, 0xc000424a20, 0xc00042df20, 0x0?, 0x0?, 0x0?)
        apps/public/Datasets/v2/datasets/datasets/Rehydrate.go:203 +0x3da
datasets_cli/v2/datasets.downloadFileWorker(0x0?, 0x0?, 0x0?, 0xc00007ad20, 0x0?)
        apps/public/Datasets/v2/datasets/datasets/Rehydrate.go:258 +0x110
created by datasets_cli/v2/datasets.downloadMultipleFiles
        apps/public/Datasets/v2/datasets/datasets/Rehydrate.go:319 +0x445
```

```
Collecting 737  records [================================================] 100% 737/737
Downloading: omalley_2021.zip    233kB done
Error: 
File unavailable ([gateway] 502 Bad Gateway): omalley_2021/ncbi_dataset/data/GCA_015062285.1/GCA_015062285.1_ASM1506228v1_genomic.fna
unexpected EOF
http2: server sent GOAWAY and closed the connection; LastStreamID=2147483647, ErrCode=NO_ERROR, debug=""
http2: server sent GOAWAY and closed the connection; LastStreamID=2147483647, ErrCode=NO_ERROR, debug=""
http2: server sent GOAWAY and closed the connection; LastStreamID=2147483647, ErrCode=NO_ERROR, debug=""
http2: server sent GOAWAY and closed the connection; LastStreamID=2147483647, ErrCode=NO_ERROR, debug=""
http2: server sent GOAWAY and closed the connection; LastStreamID=2147483647, ErrCode=NO_ERROR, debug=""
http2: server sent GOAWAY and closed the connection; LastStreamID=2147483647, ErrCode=NO_ERROR, debug=""
http2: server sent GOAWAY and closed the connection; LastStreamID=2147483647, ErrCode=NO_ERROR, debug=""
http2: server sent GOAWAY and closed the connection; LastStreamID=2147483647, ErrCode=NO_ERROR, debug=""
File unavailable ([gateway] 504 Gateway Timeout): omalley_2021/ncbi_dataset/data/GCA_015061365.1/GCA_015061365.1_ASM1506136v1_genomic.fna
http2: server sent GOAWAY and closed the connection; LastStreamID=189, ErrCode=unknown error code 0xfffffc7a, debug="The user callback function failed"
http2: server sent GOAWAY and closed the connection; LastStreamID=189, ErrCode=unknown error code 0xfffffc7a, debug="The user callback function failed"
http2: server sent GOAWAY and closed the connection; LastStreamID=189, ErrCode=unknown error code 0xfffffc7a, debug="The user callback function failed"
http2: server sent GOAWAY and closed the connection; LastStreamID=189, ErrCode=unknown error code 0xfffffc7a, debug="The user callback function failed"
http2: server sent GOAWAY and closed the connection; LastStreamID=189, ErrCode=unknown error code 0xfffffc7a, debug="The user callback function failed"
http2: server sent GOAWAY and closed the connection; LastStreamID=189, ErrCode=unknown error code 0xfffffc7a, debug="The user callback function failed"
http2: server sent GOAWAY and closed the connection; LastStreamID=2147483647, ErrCode=NO_ERROR, debug=""
http2: server sent GOAWAY and closed the connection; LastStreamID=2147483647, ErrCode=NO_ERROR, debug=""
http2: server sent GOAWAY and closed the connection; LastStreamID=2147483647, ErrCode=NO_ERROR, debug=""
unexpected EOF
unexpected EOF
unexpected EOF
unexpected EOF
unexpected EOF
unexpected EOF
unexpected EOF
unexpected EOF
unexpected EOF
unexpected EOF
unexpected EOF
http2: server sent GOAWAY and closed the connection; LastStreamID=2147483647, ErrCode=NO_ERROR, debug=""
unexpected EOF
unexpected EOF
unexpected EOF
unexpected EOF
unexpected EOF
```

Could you take a look?

_Originally posted by @ganiatgithub in https://github.com/ncbi/datasets/issues/183#issuecomment-1537279772_

**Comment by dsbard** [comment]
Hi, 

I am receiving a similar error when using version `datasets version: 15.9.1`

**Comment by ericcox1** [comment]
Hi Dino,

Thanks for commenting on this issue. We have made some changes to the rehydration process in 15.10.0 that we believe should help this problem.

We are also working on fixing an issue with resuming rehydration that we hope to release to production within a week.

If you don't mind, please update to the latest version of the client and let me know how it goes.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)

**Comment by dsbard** [comment]
Sorry for the delayed response.

Yes! I was able to download some large collections (all lactobacillus) after updating to 15.10.0
I will be doing some more downloading/rehydrating this week and will post here if I catch a similar error.

Thanks again Eric!
