### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference - rehydrate 

### ISSUE THREAD

**Issue by krithikaarumugam** [ncbi/datasets#260]
Hi,

I've been trying to download bacterial genomes using `datasets` version 15.13.1. I ran

``` ./datasets_15.13.0 download genome taxon 2 --dehydrated --filename bacteria.zip --assembly-level complete,chromosome,scaffold,contig```

followed by unzip,
```unzip bacteria.zip -d bacteria```

and rehydrate,
```./datasets_15.13.1 rehydrate --directory bacteria --max-workers 5 --debug ```

I get the following error when using 'rehydrate' in the midst of downloading (```Completed 261790 of 2042395 [====>-------------------------------------------]  13%```)

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x92c979]

goroutine 162 [running]:
datasets_cli/v2/datasets.baseRetryPolicy(...)
        apps/public/Datasets/v2/datasets/datasets/root.go:229
datasets_cli/v2/datasets.DefaultRetryPolicy({0xb9dfb0, 0xc0000361b0}, 0x0, {0xc0025f9980?, 0x4e2dc7?})
        apps/public/Datasets/v2/datasets/datasets/root.go:199 +0x59
github.com/hashicorp/go-retryablehttp.(*Client).Do(0xc0000300e0, 0xc002c495a8)
        external/com_github_hashicorp_go_retryablehttp/client.go:641 +0x61e
github.com/hashicorp/go-retryablehttp.(*RoundTripper).RoundTrip(0xc00cd3e000, 0xc002e10c00?)
        external/com_github_hashicorp_go_retryablehttp/roundtripper.go:47 +0x7d
datasets_cli/v2/datasets.LoggingRoundTripper.RoundTrip({{0xb98260?, 0xc00cd3e000?}}, 0xc002a41f00)
        apps/public/Datasets/v2/datasets/datasets/root.go:530 +0x21d
net/http.send(0xc002a41f00, {0xb9a9e0, 0xc0002980a0}, {0xa86a00?, 0xc01578d901?, 0x0?})
        GOROOT/src/net/http/client.go:252 +0x5d8
net/http.(*Client).send(0xc00cd09740, 0xc002a41f00, {0xc00428b1e0?, 0xc000062500?, 0x0?})
        GOROOT/src/net/http/client.go:176 +0x9b
net/http.(*Client).do(0xc00cd09740, 0xc002a41f00)
        GOROOT/src/net/http/client.go:725 +0x8f5
net/http.(*Client).Do(...)
        GOROOT/src/net/http/client.go:593
datasets_cli/v2/datasets.processHTTPRequest(0xa36c60?, 0xc002e10c00?)
        apps/public/Datasets/v2/datasets/datasets/Rehydrate.go:153 +0xb9
datasets_cli/v2/datasets.downloadFileWorker.func2(0xc000036270, 0xc01578df38, 0xc0005d6000, 0xc01578df20, 0xc00cd09740?, 0xc0001e0000?, 0xc000814480?)
        apps/public/Datasets/v2/datasets/datasets/Rehydrate.go:203 +0x390
datasets_cli/v2/datasets.downloadFileWorker(0x0?, 0x0?, 0x0?, 0xc000814480, 0x0?)
        apps/public/Datasets/v2/datasets/datasets/Rehydrate.go:285 +0x110
created by datasets_cli/v2/datasets.downloadMultipleFiles
        apps/public/Datasets/v2/datasets/datasets/Rehydrate.go:373 +0x83e
```

Any help would be greatly appreciated. Thank you.

Regards,
Krithika

**Comment by ericcox1** [comment]
Hi Krithika,

Thanks for opening this issue. 

This is a large dataset (possibly >10 TB). You might want to confirm that you have sufficient hard drive space. If that's not the problem, you should be able to resume the rehydration after seeing this error.

We do plan to improve our error handling for cases like this, and in the long-term we are thinking about ways to improve our delivery of especially large datasets like this.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)

**Comment by misson3** [comment]
Hello.

I encountered similar issue with much smaller dataset which is from 14 Staphylococcus argenteus records (to retrieve genome and seq-report files). 

```bash
# My machine environment is (from platform module on python),
platform.platform() -> 'Windows-10-10.0.19041-SP0'
platform.processor() -> 'Intel64 Family 6 Model 142 Stepping 12, GenuineIntel'
platform.machine() -> 'AMD64'

# command version
$ datasets --version
datasets version: 15.18.0

# command to get dehydrated file
datasets download genome \
taxon "Staphylococcus argenteus" \
--api-key $apikey \
--assembly-level complete \
--assembly-source RefSeq \
--exclude-atypical \
--include genome,seq-report \
--filename sargenteus-14-dehydrated.zip \
--dehydrated \
--preview
# stdout
Collecting 14  records [================================================] 100% 14/14
{"resource_updated_on":"2023-09-11T09:30:15Z","record_count":14,"estimated_file_size_mb":11,"included_data_files":{"all_genomic_fasta":{"file_count":1,"size_mb":10.767868}}}
# the file will be about 11mb <- much smaller than 10TB

# I removed the '--preview' flag to download sargenteus-14-dehydtated.zip
# unzip the file as sargenteus-14-de-rehydrated,
# then tried,
datasets rehydrate --api-key $apikey \
--directory './sargenteus-14-de-rehydrated'

# and got this.
Found 28 of 28 files for rehydration
Completed 0 of 28 [------------------------------------------------]   0%
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x934a99]

goroutine 43 [running]:
datasets_cli/v2/datasets.baseRetryPolicy(...)
        apps/public/Datasets/v2/datasets/datasets/root.go:229
datasets_cli/v2/datasets.DefaultRetryPolicy({0xbafb90, 0xc0000bc110}, 0x0, {0xc0000b75e0?, 0x4ee727?})
        apps/public/Datasets/v2/datasets/datasets/root.go:199 +0x59
github.com/hashicorp/go-retryablehttp.(*Client).Do(0xc00029a150, 0xc0000a70b0)
        external/com_github_hashicorp_go_retryablehttp/client.go:641 +0x61e
github.com/hashicorp/go-retryablehttp.(*RoundTripper).RoundTrip(0xc00029c090, 0xc0002133e0?)
        external/com_github_hashicorp_go_retryablehttp/roundtripper.go:47 +0x7d
datasets_cli/v2/datasets.LoggingRoundTripper.RoundTrip({{0xba9e80?, 0xc00029c090?}}, 0xc00022c400)
        apps/public/Datasets/v2/datasets/datasets/root.go:530 +0x21d
net/http.send(0xc00022c400, {0xbac620, 0xc0002860b0}, {0xa93840?, 0x1?, 0x0?})
        GOROOT/src/net/http/client.go:252 +0x5d8
net/http.(*Client).send(0xc00029ec30, 0xc00022c400, {0x0?, 0x8?, 0x0?})
        GOROOT/src/net/http/client.go:176 +0x9b
net/http.(*Client).do(0xc00029ec30, 0xc00022c400)
        GOROOT/src/net/http/client.go:725 +0x8f5
net/http.(*Client).Do(...)
        GOROOT/src/net/http/client.go:593
datasets_cli/v2/datasets.processHTTPRequest(0xa41fe0?, 0xc0002133e0?)
        apps/public/Datasets/v2/datasets/datasets/Rehydrate.go:153 +0xb9
datasets_cli/v2/datasets.downloadFileWorker.func2(0xc0002820d0, 0xc000259f38, 0xc000095ec0, 0xc000259f20, 0x0?, 0x0?, 0x0?)
        apps/public/Datasets/v2/datasets/datasets/Rehydrate.go:203 +0x390
datasets_cli/v2/datasets.downloadFileWorker(0x0?, 0x0?, 0x0?, 0xc0002a0240, 0x0?)
        apps/public/Datasets/v2/datasets/datasets/Rehydrate.go:285 +0x110
created by datasets_cli/v2/datasets.downloadMultipleFiles
        apps/public/Datasets/v2/datasets/datasets/Rehydrate.go:373 +0x83e

```
The same worked well on Debian (I really like dehydration-rehydration method!), but I would like to make this work on Windows OS for my colleagues.
Any suggestion would be helpful.

Thanks!

**Comment by ericcox1** [comment]
Hi @misson3,

Thanks for your comment and thank you for reporting this bug. 

There is a known bug with rehydration on Windows. I will comment on this thread when we have a fix ready.

In the meantime, you should be able to download this relatively small genome data package directly, without using the "dehydration-rehydration" method.

Best,
Eric

**Comment by krithikaarumugam** [comment]
Hi @ericcox1,

Thanks for your reply. I managed to download the bacterial genomes after resuming `hydration` a few times (~16). The data set was ~11 TB.

Regards,
Krithika

**Comment by qbilius** [comment]
I ran into a similar issue where rehydration produces the above reported runtime error. Manually restarting the process works fine but who wants to babysit the process like this? :) Here's a script that worked for me:

```
#!/bin/bash

while true; do
    # Run the command and capture its output in real-time
    datasets rehydrate --directory bacteria 2>&1 | while IFS= read -r line; do
        # Print the line in real-time
        echo "$line"

        # Check if the line contains an error message
        if [[ "$line" == *"panic: runtime error"* ]]; then
            # If error is found, exit the inner loop with a specific exit code
            exit 42
        fi
    done

    # Check the exit code of the inner loop
    if [[ $? -ne 42 ]]; then
        # If exit code is not 42, it means the command completed successfully
        break
    fi

    echo "Error detected. Resuming..."
    sleep 1  # Small delay before retyring
done

echo "Command completed successfully."
```

**Comment by mtntsuchiya** [comment]
Hi @qbilius ,

Thanks for sharing your script and letting us know of the issue. 
Are you running the rehydration on Windows, Mac or Linux? 

Thanks!
Mirian

Mirian T. N. Tsuchiya, PhD [Contractor] (she/her/hers)
NCBI Datasets
NIH/NLM/NCBI

**Comment by qbilius** [comment]
Running on Linux. I get the error repeatedly every ~20k genomes or so (trying to rehydrate all bacterial genomes). The datasets version should be the latest as I downloaded it a week ago.

**Comment by mtntsuchiya** [comment]
Thanks for the info. 

We have very frequent version releases (the latest is from yesterday). Could you please send us:
- the version you're using
- the full error message  (I understanding you're running your script so you don't have to babysit the rehydration if it fails, but would you mind doing that once so we can have a better understanding of the error?)
- Also, the PHID. when you re-run, could you please use the flag `--debug`, so we can see the PHID and use that info look at what's going on internally?

Thank you so much!

**Comment by qbilius** [comment]
Hi Mirian,

Sorry for a slow response, I somehow missed your comment.

I reran rehydrate with the debug flag. This is the end of the output just before throwing an error:

```
Completed 244393 of 2154502 [===>--------------------------------------------]  11%

GET /datasets/fetch_h/R2V0UmVtb3RlRGF0YWZpbGU/eNqTKuUqzktOytROKymw0tdPT83Lz00t1k_MydF3d3bUNzAy1Tc0NN
c3NTAF8eOBfCAXyNMzjA9wCTEwMDQxNDA2sdAzJCAdDzY5M1kvLS9RL73KgNGCEQAUyiBU HTTP/1.1
Host: api.ncbi.nlm.nih.gov
User-Agent: Go-http-client/1.1
Ncbi-Phid: C448BFB91322986DFAE908FA
X-Datasets-Client: datasets-cli
X-Datasets-Client-Arch: amd64
X-Datasets-Client-Cmd: rehydrate --directory tmp --debug
X-Datasets-Client-Os: linux
X-Datasets-Client-Version: 16.25.0
X-Datasets-Gzip-Request: true
Accept-Encoding: gzip

Completed 244394 of 2154502 [===>--------------------------------------------]  11%

HTTP/1.1 200 OK
Content-Length: 483437
Accept-Ranges: bytes
Access-Control-Allow-Headers: RANGE, Cache-control, If-None-Match, Content-Type
Access-Control-Allow-Methods: GET,POST,PUT,OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Content-Length, Content-Range, Content-Type
Content-Type: application/x-gzip
Date: Thu, 22 Aug 2024 18:09:58 GMT
Etag: "7606d-5e82e86243655"
Last-Modified: Thu, 08 Sep 2022 18:23:20 GMT
Server: Apache
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload

Completed 244394 of 2154502 [===>--------------------------------------------]  11%
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xade558]

goroutine 58 [running]:
datasets_cli/v2/datasets.baseRetryPolicy(0xc00358f2f0?, {0xc00358f198?, 0xc00358f258?})
        apps/public/Datasets/v2/datasets/datasets/root.go:218 +0x18
datasets_cli/v2/datasets.DefaultRetryPolicy({0xdf90b0, 0xc0000340e0}, 0x13959c0?, {0xdf40c0, 0xc00f3
15530})
        apps/public/Datasets/v2/datasets/datasets/root.go:188 +0x71
github.com/hashicorp/go-retryablehttp.(*Client).Do(0xc00027c000, 0xc00ed7e7b0)
        external/com_github_hashicorp_go_retryablehttp/client.go:641 +0x61e
github.com/hashicorp/go-retryablehttp.(*RoundTripper).RoundTrip(0xc007be4000, 0xc00e75dfb0?)
        external/com_github_hashicorp_go_retryablehttp/roundtripper.go:47 +0x7d
datasets_cli/v2/datasets.LoggingRoundTripper.RoundTrip({{0xdf10a0?, 0xc007be4000?}}, 0xc00de15f00)
        apps/public/Datasets/v2/datasets/datasets/root.go:518 +0x21d
net/http.send(0xc00de15f00, {0xdf4580, 0xc0002920a0}, {0xcab5c0?, 0xc00358f901?, 0x0?})
        GOROOT/src/net/http/client.go:252 +0x5d8
net/http.(*Client).send(0xc007bd8210, 0xc00de15f00, {0xc001c52ea0?, 0xc000054000?, 0x0?})
        GOROOT/src/net/http/client.go:176 +0x9b
net/http.(*Client).do(0xc007bd8210, 0xc00de15f00)
        GOROOT/src/net/http/client.go:725 +0x8f5
net/http.(*Client).Do(...)
        GOROOT/src/net/http/client.go:593
datasets_cli/v2/datasets.processHTTPRequest(0xc418c0?, 0xc00e75dfb0?)
        apps/public/Datasets/v2/datasets/datasets/Rehydrate.go:153 +0xb9
datasets_cli/v2/datasets.downloadFileWorker.func2(0xc0000341a0, 0xc00358ff38, 0xc0000dea80, 0xc00358
ff20, 0xc007bd8210?, 0xc000258000?, 0xc000730120?)
        apps/public/Datasets/v2/datasets/datasets/Rehydrate.go:203 +0x3b0
datasets_cli/v2/datasets.downloadFileWorker(0x0?, 0x0?, 0x0?, 0xc000730120, 0x0?)
        apps/public/Datasets/v2/datasets/datasets/Rehydrate.go:280 +0x110
created by datasets_cli/v2/datasets.downloadMultipleFiles
        apps/public/Datasets/v2/datasets/datasets/Rehydrate.go:368 +0x83e
```

PHID is C448BFB91322986DFAE908FA
datasets version: 16.25.0
