### ISSUE TITLE
--preview option breaks download

### ISSUE THREAD

**Issue by BioinformaticsPlatformWIV-ISP** [ncbi/datasets#314]
Following command:
`datasets download genome accession --inputfile accessions.txt --include none --preview`
gives a panic
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x967e90]

goroutine 1 [running]:
datasets_cli/v2/datasets.(*DownloadSummaryInterface).ProcessPage(0xc0003cef00, 0x3e8?)
        apps/public/Datasets/v2/datasets/datasets/DownloadGenome.go:53 +0x2d0
datasets_cli/v2/datasets.ProcessPages[...]({0xc29450, 0xc0003b8fc0}, {0xc257c0, 0xc00000e260}, {0xc28f40, 0xc0003cef00?}, 0x7fffffffffffffff, 0x0)
        apps/public/Datasets/v2/datasets/datasets/PageProcessor.go:446 +0x47d
datasets_cli/v2/datasets.ProcessAllPages[...](...)
        apps/public/Datasets/v2/datasets/datasets/PageProcessor.go:373
datasets_cli/v2/datasets.getDownloadSummary({0xc29450, 0xc0003b8fc0})
        apps/public/Datasets/v2/datasets/datasets/DownloadGenome.go:139 +0x215
datasets_cli/v2/datasets.createDownloadGenomeAccessionCmd.func1(0xc000033800?, {0xc0001969b0?, 0x0?, 0x5?})
        apps/public/Datasets/v2/datasets/datasets/DownloadGenomeAccession.go:52 +0x265
github.com/spf13/cobra.(*Command).execute(0xc000033800, {0xc000196960, 0x5, 0x5})
        external/com_github_spf13_cobra/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x1093920)
        external/com_github_spf13_cobra/command.go:1068 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        external/com_github_spf13_cobra/command.go:992
datasets_cli/v2/datasets.Execute()
        apps/public/Datasets/v2/datasets/datasets/root.go:495 +0x25
main.main()
        apps/public/Datasets/v2/cmd/datasets/main.go:10 +0x17
```

leaving out the `--preview` option, it works as intended:
```
Collecting 2,807 genome records [================================================] 100% 2807/2807
Downloading: ncbi_dataset.zip    1.27MB valid zip structure -- files not checked
Validating package [================================================] 100% 3/3
```

[accessions.txt](https://github.com/ncbi/datasets/files/14313419/accessions.txt)
[debug.txt](https://github.com/ncbi/datasets/files/14313441/debug.txt)

**Comment by ericcox1** [comment]
Hi @BioinformaticsPlatformWIV-ISP,

Thanks for opening this issue. I was able to reproduce this bug. We will try to schedule a fix soon and I will comment on this thread when it's ready.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)

**Comment by ericcox1** [comment]
Hi @BioinformaticsPlatformWIV-ISP,

This bug has been fixed. We recommend that you update to the latest version of the client, 16.8.1.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)
