### ISSUE TITLE
npm OpenAPI build script fails to run

### ISSUE THREAD

**Issue by pipparichter** [ncbi/datasets#378]
I am running the npm script [here](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/languages/) in order to set up a Python library for working with NCBI datasets, but the build fails with this error:

`SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
`
I have never used OpenAPI before, and am wondering if anyone knows what could have caused this. Thanks in advance!

**Comment by ericcox1** [comment]
Hi @pipparichter,

Thanks for opening this issue.

We were unable to reproduce this issue. Please check what version of nodejs you are using. We are currently using version 18 of nodejs and we recommend using that version.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)
