### ISSUE TITLE
Problem in the configuration step

### ISSUE THREAD

**Issue by arturomarin** [ncbi/datasets#40]
Hi, 

very interesting project. I have installed in a conda env (with python 3.6.12) with:

`pip install ncbi-datasets-pylib`

I think that now I need to configure it with the script of the web page:
https://github.com/ncbi/datasets/tree/master/client_docs/python#getting-started
in the step "Getting Started", but python give me an error:

```
Traceback (most recent call last):
  File "NCBI_Dataset_configuration.py", line 20, in <module>
    api_instance = ncbi.datasets.GeneApi(api_client)
AttributeError: module 'ncbi.datasets' has no attribute 'GeneApi'

```

Any suggestion?

**Comment by BradHolmes** [comment]
Hi,

Thank you for giving NCBI Datasets a try.  I'm sorry you have encountered a problem with the python library.  I think we'll need to fix up the getting-started page, and provide better examples.

However, I would expect `GeneApi` to be a member of `ncbi.datasets`.  Let's see if we can try to sort that out.  A few questions should get us started.

1. Which version of the library do you have installed?  
2. What do you get for `dir(ncbi.datasets)`?
3. What do you get for `dir(ncbi.datasets.openapi)`?

**Comment by arturomarin** [comment]
Hi BradHolmes,

thanks for your help. 

1. Which version of the library do you have installed? ncbi-datasets-pylib 3.64.1
2. What do you get for dir(ncbi.datasets)? 
3. What do you get for dir(ncbi.datasets.openapi)?
```
>>> import ncbi.datasets
>>> dir(ncbi.datasets)
['AnnotationForAssemblyType', 'ApiClient', 'ApiException', 'ApiKeyError', 'ApiTypeError', 'ApiValueError', 'AssemblyDatasetDescriptorsApi', 'AssemblyDatasetDescriptorsRequestContentType', 'AssemblyDatasetRequestResolution', 'Configuration', 'DownloadApi', 'DownloadSummaryDehydrated', 'DownloadSummaryError', 'DownloadSummaryHydrated', 'GeneDatasetDescriptorsApi', 'GeneDatasetRequestSeqType', 'GeneDescriptorGeneType', 'OpenApiException', 'OrganismCounts', 'OrganismRankType', 'TaxTreeApi', 'TranscriptTranscriptType', 'V1alpha1AnnotationForAssembly', 'V1alpha1AnnotationForAssemblyFile', 'V1alpha1AssemblyDatasetAvailability', 'V1alpha1AssemblyDatasetDescriptor', 'V1alpha1AssemblyDatasetDescriptors', 'V1alpha1AssemblyDatasetDescriptorsFilter', 'V1alpha1AssemblyDatasetRequest', 'V1alpha1DownloadSummary', 'V1alpha1GeneDatasetRequest', 'V1alpha1GeneDescriptor', 'V1alpha1GeneDescriptors', 'V1alpha1MaturePeptide', 'V1alpha1NomenclatureAuthority', 'V1alpha1Organism', 'V1alpha1Orientation', 'V1alpha1Protein', 'V1alpha1Range', 'V1alpha1SeqRangeSet', 'V1alpha1Transcript', 'VirusDatasetApi', 'VirusDownloadApi', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'absolute_import', 'api', 'api_client', 'configuration', 'exceptions', 'models', 'rest']
>>> dir(ncbi.datasets.openapi)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'ncbi.datasets' has no attribute 'openapi'

```
by the way I am in an iMac with macOS 10.15.7 .

**Comment by BradHolmes** [comment]
OK, so `v3.64.1` is a pretty old version, and would explain your difficulty.  

Can you [update it to the latest version](https://pypi.org/project/ncbi-datasets-pylib/)?

**Comment by arturomarin** [comment]
thanks. I need to create another conda env with Python >= 3.7 . I will try it and tell you the result.

**Comment by arturomarin** [comment]
Hi, 

now I have a conda env with python 3.9.2. 

1. Which version of the library do you have installed?   ncbi-datasets-pylib 11.6.0
2. What do you get for dir(ncbi.datasets)?
3. What do you get for dir(ncbi.datasets.openapi)?

```
>>> import ncbi.datasets
>>> dir(ncbi.datasets)
['ApiClient', 'ApiException', 'ApiKeyError', 'ApiTypeError', 'ApiValueError', 'AssemblyDatasetRequestResolution', 'AssemblyMetadataRequestBioprojects', 'Configuration', 'DatasetDownloadApi', 'Datasetsv1alpha1Accessions', 'Datasetsv1alpha1Annotation', 'DownloadSummaryDehydrated', 'DownloadSummaryHydrated', 'ErrorAssemblyErrorCode', 'ErrorGeneErrorCode', 'ErrorVirusErrorCode', 'GeneApi', 'GeneDatasetRequestSort', 'GeneDatasetRequestSortField', 'GeneDatasetRequestSymbolsForTaxon', 'GeneDescriptorGeneType', 'GeneDescriptorRnaType', 'GenomeApi', 'GenomicRegionGenomicRegionType', 'MicroBiggeDatasetRequestElementFlankConfig', 'OpenApiException', 'OrganismCountByType', 'OrganismCountType', 'OrganismCounts', 'OrganismRankType', 'ProkaryoteApi', 'ProkaryoteGeneRequestGeneFlankConfig', 'ProtobufAny', 'RpcStatus', 'SciNameAndIdsSciNameAndId', 'StreamResultOfProtobufBytesValue', 'StreamResultOfV1alpha1TabularOutput', 'TranscriptTranscriptType', 'V1alpha1AnnotatedAssemblies', 'V1alpha1AnnotationForAssembly', 'V1alpha1AnnotationForAssemblyFile', 'V1alpha1AnnotationForAssemblyType', 'V1alpha1AnnotationForVirusType', 'V1alpha1AssemblyDatasetAvailability', 'V1alpha1AssemblyDatasetDescriptor', 'V1alpha1AssemblyDatasetDescriptors', 'V1alpha1AssemblyDatasetDescriptorsFilter', 'V1alpha1AssemblyDatasetDescriptorsRequestContentType', 'V1alpha1AssemblyDatasetRequest', 'V1alpha1AssemblyMatch', 'V1alpha1AssemblyMetadata', 'V1alpha1AssemblyMetadataRequestContentType', 'V1alpha1BioProject', 'V1alpha1BioProjectLineage', 'V1alpha1DownloadSummary', 'V1alpha1Error', 'V1alpha1Fasta', 'V1alpha1GeneDatasetRequest', 'V1alpha1GeneDatasetRequestContentType', 'V1alpha1GeneDescriptor', 'V1alpha1GeneDescriptors', 'V1alpha1GeneMatch', 'V1alpha1GeneMetadata', 'V1alpha1GenomicLocation', 'V1alpha1GenomicRegion', 'V1alpha1MaturePeptide', 'V1alpha1Message', 'V1alpha1MicroBiggeDatasetRequestFileType', 'V1alpha1NomenclatureAuthority', 'V1alpha1Organism', 'V1alpha1Orientation', 'V1alpha1OrthologRequestContentType', 'V1alpha1OrthologSet', 'V1alpha1ProkaryoteGeneRequest', 'V1alpha1Protein', 'V1alpha1Range', 'V1alpha1SciNameAndIds', 'V1alpha1SeqRangeSet', 'V1alpha1SortDirection', 'V1alpha1TableFormat', 'V1alpha1TabularOutput', 'V1alpha1Transcript', 'V1alpha1VersionReply', 'V1alpha1VirusTableField', 'V1alpha1Warning', 'VersionApi', 'VirusApi', 'WarningGeneWarningCode', 'WarningReplacedId', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'absolute_import', 'api', 'api_client', 'configuration', 'exceptions', 'models', 'openapi', 'rest']
>>> dir(ncbi.datasets.openapi)
['ApiClient', 'ApiException', 'ApiKeyError', 'ApiTypeError', 'ApiValueError', 'AssemblyDatasetRequestResolution', 'AssemblyMetadataRequestBioprojects', 'Configuration', 'DatasetDownloadApi', 'Datasetsv1alpha1Accessions', 'Datasetsv1alpha1Annotation', 'DownloadSummaryDehydrated', 'DownloadSummaryHydrated', 'ErrorAssemblyErrorCode', 'ErrorGeneErrorCode', 'ErrorVirusErrorCode', 'GeneApi', 'GeneDatasetRequestSort', 'GeneDatasetRequestSortField', 'GeneDatasetRequestSymbolsForTaxon', 'GeneDescriptorGeneType', 'GeneDescriptorRnaType', 'GenomeApi', 'GenomicRegionGenomicRegionType', 'MicroBiggeDatasetRequestElementFlankConfig', 'OpenApiException', 'OrganismCountByType', 'OrganismCountType', 'OrganismCounts', 'OrganismRankType', 'ProkaryoteApi', 'ProkaryoteGeneRequestGeneFlankConfig', 'ProtobufAny', 'RpcStatus', 'SciNameAndIdsSciNameAndId', 'StreamResultOfProtobufBytesValue', 'StreamResultOfV1alpha1TabularOutput', 'TranscriptTranscriptType', 'V1alpha1AnnotatedAssemblies', 'V1alpha1AnnotationForAssembly', 'V1alpha1AnnotationForAssemblyFile', 'V1alpha1AnnotationForAssemblyType', 'V1alpha1AnnotationForVirusType', 'V1alpha1AssemblyDatasetAvailability', 'V1alpha1AssemblyDatasetDescriptor', 'V1alpha1AssemblyDatasetDescriptors', 'V1alpha1AssemblyDatasetDescriptorsFilter', 'V1alpha1AssemblyDatasetDescriptorsRequestContentType', 'V1alpha1AssemblyDatasetRequest', 'V1alpha1AssemblyMatch', 'V1alpha1AssemblyMetadata', 'V1alpha1AssemblyMetadataRequestContentType', 'V1alpha1BioProject', 'V1alpha1BioProjectLineage', 'V1alpha1DownloadSummary', 'V1alpha1Error', 'V1alpha1Fasta', 'V1alpha1GeneDatasetRequest', 'V1alpha1GeneDatasetRequestContentType', 'V1alpha1GeneDescriptor', 'V1alpha1GeneDescriptors', 'V1alpha1GeneMatch', 'V1alpha1GeneMetadata', 'V1alpha1GenomicLocation', 'V1alpha1GenomicRegion', 'V1alpha1MaturePeptide', 'V1alpha1Message', 'V1alpha1MicroBiggeDatasetRequestFileType', 'V1alpha1NomenclatureAuthority', 'V1alpha1Organism', 'V1alpha1Orientation', 'V1alpha1OrthologRequestContentType', 'V1alpha1OrthologSet', 'V1alpha1ProkaryoteGeneRequest', 'V1alpha1Protein', 'V1alpha1Range', 'V1alpha1SciNameAndIds', 'V1alpha1SeqRangeSet', 'V1alpha1SortDirection', 'V1alpha1TableFormat', 'V1alpha1TabularOutput', 'V1alpha1Transcript', 'V1alpha1VersionReply', 'V1alpha1VirusTableField', 'V1alpha1Warning', 'VersionApi', 'VirusApi', 'WarningGeneWarningCode', 'WarningReplacedId', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'absolute_import', 'api', 'api_client', 'configuration', 'exceptions', 'models', 'rest']

```

But now I have other error when try getting-started:

```
Traceback (most recent call last):
  File "/Users/arturo/bioinfo/NCBI_Dataset_configuration.py", line 6, in <module>
    from ncbi.datasets.rest import ApiException

```
it just if it is useful for you. I am interesting in this library for download genome assembly of viruses and their annotated files using its taxid, I not sure if I can do with this library or maybe I need to use Entrez Utilities.

thanks

**Comment by BradHolmes** [comment]
Hi,

Sorry for the delay in responding to you.  

If I understand correctly, I believe you can do what you want most easily through NCBI Datasets.  The contents of the SARS-CoV-2 Genome package includes:

```
sars-cov-2/
|-- README.md
`-- ncbi_dataset
    `-- data
        |-- cds.fna
        |-- data_report.jsonl
        |-- dataset_catalog.json
        |-- genomic.fna
        |-- pdb
        |   `-- *.pdb
        |-- protein.faa
        |-- protein.gpff
        `-- virus_dataset.md
```
Are these the files you are looking for?  And do you prefer to download through `python` code (if so, I'll come up with a working snippet for you), or do you want to explore using the [command line app](https://www.ncbi.nlm.nih.gov/datasets/docs/command-line-start/) `datasets`?

**Comment by arturomarin** [comment]
Hi, 

sorry for the delay too. I am looking for  .fna file and for .gtf and / or .gff files. The last two don't appeared  in the contents of the SARS-CoV-2 Genome package includes. I started doing this with Entrez Direct (esearch and efetch), but I ran into other problems.  I am interested in developing a software and one of the parts is that it can download the assembled (.fna) and annotated (.gtf and / or .gff) genome of any virus. The problem with Entrez Direct is that it seems that in some cases there are several genomes available, but there is no reference genome, and I don't know which one to download. 

In any case, if this were possible with NCBI Datasets, the best way would be to implement it in Python since I am developing my program in Python.

**Comment by BradHolmes** [comment]
Hi,

You are right, the Virus Genome package does not contain gtf/gff files.  We will look into adding those files.

For a code snippet to download viral data by taxon, see the [SARS-CoV-2](https://api.ncbi.nlm.nih.gov/datasets/docs/how-tos/virus/get-sars2-genomes/#download-by-taxon) genomes HowTo, and click the python tab.

Good luck!
Brad
